# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
                ('psyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Psycologist')),
            ],
        ),
    ]
