# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='value',
            field=models.CharField(choices=[(1, 'psycologist'), (2, 'client')], default=2, max_length=2),
        ),
    ]
