# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='document',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
        migrations.AddField(
            model_name='psycologist',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='documenta'),
        ),
        migrations.AddField(
            model_name='psycologist',
            name='verified',
            field=models.CharField(choices=[(0, 'not verified'), (1, 'verified')], default=0, max_length=2),
        ),
    ]
