# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170305_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psycologist',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='document'),
        ),
    ]
