# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170305_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psycologist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psycologist', to=settings.AUTH_USER_MODEL),
        ),
    ]
