# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170305_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prof',
            field=models.CharField(choices=[(0, 'client'), (1, 'psycologist')], default=0, max_length=2),
        ),
    ]
