# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textart',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
    ]
