# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.Entry'),
            preserve_default=False,
        ),
    ]
