# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 11:59
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='short_text',
        ),
        migrations.AddField(
            model_name='entry',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
