# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20170303_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.DeleteModel(
            name='ExampleNonUploadModel',
        ),
    ]
