# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20170303_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioart',
            name='article',
        ),
        migrations.RemoveField(
            model_name='imageart',
            name='article',
        ),
        migrations.RemoveField(
            model_name='textart',
            name='article',
        ),
        migrations.RemoveField(
            model_name='videoart',
            name='article',
        ),
        migrations.DeleteModel(
            name='Audioart',
        ),
        migrations.DeleteModel(
            name='Imageart',
        ),
        migrations.DeleteModel(
            name='Textart',
        ),
        migrations.DeleteModel(
            name='Videoart',
        ),
    ]
